### ISSUE TITLE
Gooogle Chrome Issue

### ISSUE THREAD

**Issue by cromaki** [Deyda/Evergreen-Script#12]
Hallo,

der Download von Google Chrome funktioniert nicht mehr. Es wird einfach übersprungen und zeigt auch keine Version mehr an in den Logs.

Gibt es hierzu einen Workaround oder hat Google etwas geändert?

Liebe Grüße

**Comment by Deyda** [comment]
Bei mir funktioniert alles. Bitte einmal den Google Chrome Download Ordner löschen.

![image](https://user-images.githubusercontent.com/59874195/142182247-d0ac860e-1179-4c1c-bd06-e181a9346ae8.png)

**Comment by cromaki** [comment]
Ich habe jetzt gerade eine neue Evergreen Instanz genommen und nur Google Chrome ausgewählt. Wird genauso übersprungen.
![Bildschirmfoto 2021-11-17 um 11 21 31](https://user-images.githubusercontent.com/94054635/142182749-e69ff935-7493-43cf-a040-9731e56b6657.png)

**Comment by cromaki** [comment]
Scheint so als ob der Fehler bei Windows liegt. Bei einem 2012 Terminal Server wird es einfach übersprungen bei 2019 nicht.

**Comment by Deyda** [comment]
Ok ich checke auch mal auf 2012

**Comment by Deyda** [comment]
Auf einem 2012er System

![image](https://user-images.githubusercontent.com/59874195/142185351-4371ca0e-7db8-4398-972f-4738bd3a9892.png)

**Comment by cromaki** [comment]
Komischerweise werden die Plugins jedesmal neu installiert - ich glaube da liegt der Fehler irgendwo

**Comment by Deyda** [comment]
Teste einfach mal ob Evergreen Powershell Module installiert ist, durch find-evergreenapp in einer Powershell Konsole

**Comment by cromaki** [comment]
Okay, daran wird es liegen er installiert er installiert komischerweise die Module nicht. Liegt es vielleicht an der Powershell version?
![Bildschirmfoto 2021-11-17 um 12 13 29](https://user-images.githubusercontent.com/94054635/142190277-7e118525-74aa-42f4-860b-1bfda3b18330.png)
.

**Comment by Deyda** [comment]
Sehr Gut möglich, habe auf meinem 2012, die folgende Version installiert.

![image](https://user-images.githubusercontent.com/59874195/142190555-9a7a01ae-2744-4d65-abaa-7c2a2173f8b2.png)

**Comment by cromaki** [comment]
Okay, werde mal versuchen ein Upgrade durchzuführen gebe dann ein Feedback ob es geklappt hat oder nicht.

**Comment by cromaki** [comment]
FYI - Funktioniert erst ab Powershell Version 5

**Comment by Deyda** [comment]
Wird in Script als Minimum Version aufgenommen, Danke.
