### ISSUE TITLE
missing langugaes

### ISSUE THREAD

**Issue by zdeneksofr** [Deyda/Evergreen-Script#14]
thanks for great job, but how to select language  (for example Polish, Bulgarian.....), which is available for SW itself (VLC, O365, Adobe reader), but thia choice is not in GUI? is it possible via editing .txt file?

**Comment by Deyda** [comment]
No, I have implemented most of the languages I can select with the Evergreen Powershell module. Which additional languages did you miss? and in which software do you miss the Polish language? can you send me a list of items? Sometimes I can't see the forest for the trees ^^

**Comment by zdeneksofr** [comment]
Hello, thansk, I´m missing Czech language (Polish was an exmaple, cause it´s bigger country than Czech rep.) for Adobe Reader, VLC, Office 365, Teams, OneDrive, 7ZIP, Split and Merge, Irfan (they exists), but i´m not sure what I´ll use in future (what apps), so the question was in general....
thanks 4 your time

**Comment by Deyda** [comment]
Pefect. Then I'll see what I can do with czech language in general and in the individual programs...let's see what the nevergreen or evergreen module can offer....

**Comment by zdeneksofr** [comment]
great, thanks a lot. if u need any kind of support (i.e. with czech language...) feel free to ask.....

**Comment by Deyda** [comment]
Implemented in Version 2.07.1
