### ISSUE TITLE
Microsoft Dot Net Framework not downloading

### ISSUE THREAD

**Issue by kevthegrump** [Deyda/Evergreen-Script#15]
Looks like the evergreen module now returns multiple installer types from the MS feed, which caused the download to fail for me.

In my environment I updated line 9592 by adding an additional filter to the where-object to remove SDK and runtime options.

$MSDotNetFrameworkD = Get-EvergreenApp -Name Microsoft.NET | Where-Object {$_.Architecture -eq "$MSDotNetFrameworkArchitectureClear" -and $_.Channel -eq "$MSDotNetFrameworkChannelClear" -**and $_.installer -eq "windowsdesktop"** }

**Comment by Deyda** [comment]
With Version 2.07 done
