### ISSUE TITLE
Feature Request - Change Vmware tools install switch to supress reboot

### ISSUE THREAD

**Issue by kevthegrump** [Deyda/Evergreen-Script#17]
Hi

Would it be possible to change the default install switch for vmware tools to supress the auto reboot? I have been using the script inside MDT and the restart breaks the task sequence, personnally I would prefer to do a manual restart after the apps are installed.

The change would be "REBOOT=ReallySuppress" instead of REBOOT=Y

**Comment by Deyda** [comment]
Done in the new coming version..

![image](https://user-images.githubusercontent.com/59874195/145597985-e56dec7b-0616-4bd2-8bfd-6d25a9c85400.png)

**Comment by kevthegrump** [comment]
wow that was fast, thanks

**Comment by Deyda** [comment]
Implemented in Version 2.07.1
