### ISSUE TITLE
Problem mit LastConfig

### ISSUE THREAD

**Issue by cromaki** [Deyda/Evergreen-Script#18]
Hallo,

ich habe Evergreen per Script auf meinen Server laufen. Da ist mir aufgefallen, dass durch die letzten Updates vom Script die Sprachen etc. nicht mehr übereinstimmen.

z.B. Mozilla Firefox auf Schwedisch etc.

Müssen die Configs nach jedem Update angepasst werden oder kann man das umgehen?

Liebe Grüße
Marko

**Comment by Deyda** [comment]
Eigentlich bleiben die Einstellungen gleich. Habe aber weitere Sprachen hinzugefügt und eigentlich eine Route eingesetzt die die Sprachen wieder auf die alte setzt. Wird aber das letzte mal sein, das dies nötig sein wird.
