### ISSUE TITLE
Zoom download error

### ISSUE THREAD

**Issue by brauki** [Deyda/Evergreen-Script#20]
<img width="677" alt="zoom-error" src="https://user-images.githubusercontent.com/33343499/148761603-b074505b-fd3a-4cd8-ad6d-189fd746a40c.PNG">

**Comment by Deyda** [comment]
![image](https://user-images.githubusercontent.com/59874195/148764970-7d40e58a-5cd6-4582-b967-cddf457a5444.png)

No Problem at my system. Plz retry it...

**Comment by brauki** [comment]
Hi was a bit slow, when i look at the source code from zoom vdi downloader and run it alone i get no vdi package displayed !

Get-NevergreenApp -Name Zoom

Result: No VDI Package avaible

if I run GetEvergreenApp -Name Zoom then a VDI client is displayed ?

of course I can change it now but it's strange !

Thanks Thomas

**Comment by Deyda** [comment]
I implement it with this line

Get-NevergreenApp -Name Zoom | Where-Object {$_.Name -like "*VDI Client"}

**Comment by brauki** [comment]
![image](https://user-images.githubusercontent.com/33343499/149161683-0a603d6b-1b72-42f8-8359-33cb43783fc9.png)

**Comment by brauki** [comment]
![image](https://user-images.githubusercontent.com/33343499/149161833-1f14d7b4-e92d-4f71-a90c-4482793ae511.png)

**Comment by brauki** [comment]
I have seen this but it does not find anything with *VDI

**Comment by Deyda** [comment]
![image](https://user-images.githubusercontent.com/59874195/149162034-a872b0ad-6dce-4068-ad0a-17e2a5bd7ba4.png)

**Comment by Deyda** [comment]
With my Evergreen Script i update the modules automatically...

**Comment by Deyda** [comment]
as you can see in my screenshot, I also only do the command...

**Comment by brauki** [comment]
Can I change the Nevergreen module to an old version?

**Comment by brauki** [comment]
When I execute this it looks like this 

![image](https://user-images.githubusercontent.com/33343499/149162890-e8d375c1-44b1-4242-89ca-19e3437a33fa.png)

**Comment by brauki** [comment]
It must be the Nevergreen module ! Can you provide me your version ?

**Comment by Deyda** [comment]
sry I do not know whats the problem of your system ^^

**Comment by Deyda** [comment]
![image](https://user-images.githubusercontent.com/59874195/149163369-d9a1cf07-1b4c-40ad-a5d8-4b2dd1eed8df.png)

**Comment by Deyda** [comment]
which version do u have ?

**Comment by brauki** [comment]
![image](https://user-images.githubusercontent.com/33343499/149164293-93dd125f-274a-424e-90e6-9fc2014faed3.png)


if i sort

![image](https://user-images.githubusercontent.com/33343499/149164471-27ac2521-1a5f-4139-ba1c-b4bc6156916a.png)

**Comment by Deyda** [comment]
delete the module and reinstall it via evergreen script.

**Comment by brauki** [comment]
Have deleted it and reinstalled same problem
