### ISSUE TITLE
"-file" Parameter don't work

### ISSUE THREAD

**Issue by Marksn1230** [Deyda/Evergreen-Script#24]
Hello,

the “-file” Parameter doesn't work any more. I scheduled it over a Task and since the last updates it stopped working.

See Screenshot in the attachment.

![Bildschirmfoto 2022-03-22 um 14 55 05](https://user-images.githubusercontent.com/102163388/159497809-7f8a5c88-6c6b-4a70-96d9-3bb6ec1a2931.png)

Best Regards

**Comment by Deyda** [comment]
2022-02-17        Rename Parameter -file to -ESfile
