### ISSUE TITLE
Script stops running during download phase

### ISSUE THREAD

**Issue by Mikey-b941** [Deyda/Evergreen-Script#25]
Hi,

I have got this running nicely but am running into some issues when downloading the updated software.  I get the attached error message which suggests some kind of rate limit from github is causing issues.   Is there anything I can do from my side?  NB this isn't consistent, sometimes it works fine, other times it fails.  Interestingly, it often seems to fail about the same point, after downloading MS Team machine-wide.

Many thanks,
![evergreen](https://user-images.githubusercontent.com/99493093/160396516-05aa94aa-0519-4687-a344-3dc4d5de1483.JPG)

   Mike

**Comment by Deyda** [comment]
Hi, I test this now in my testlab. seems to be an error from the powershell module

**Comment by Deyda** [comment]
Hmmm just ran the script 30 times in one minute to download ms teams and got no error.

**Comment by Deyda** [comment]
Can you please make a screenshot of your selected software (GUI)? maybe is it the software after ms teams.

**Comment by Deyda** [comment]
Hmmm i just can't recreate it. Can you try it without the proxy?

**Comment by Mikey-b941** [comment]
Unfortunately, not easily.  The proxy is a transparent web-hosted proxy and
all internet-bound traffic is routed that way automatically, with no local
settings on machines to point it there.

I wonder if the second error is likely to be the cause, reason being that I
do see that error sometimes when connecting to websites from a browser.
They may be able to exclude any github URLs from the proxy.

**Comment by Deyda** [comment]
Thx bro. I will check the notepad++ path.

**Comment by Deyda** [comment]
does not seem to be a general problem. Just tested again with Notepad++ on me..all good. But I also have no proxy here
