### ISSUE TITLE
Microsoft Edge doesn't jump to Stable 100

### ISSUE THREAD

**Issue by cromaki** [Deyda/Evergreen-Script#27]
Hello,

Evergreen Script won't download Microsoft Edge Stable 100 Version, it stays at 99.0.1150.55.

Best Regards

**Comment by Deyda** [comment]
![image](https://user-images.githubusercontent.com/59874195/163941274-182118ae-e50d-45e3-9d8c-0847049922c8.png)
The Enterprise Version is 99.x. Only the Consumer Version is at the moment on 100.xx
![image](https://user-images.githubusercontent.com/59874195/163941364-40f6569a-2995-43ff-8dfe-b4356b3c5c03.png)

**Comment by Deyda** [comment]
I change the version from enterprise to consumer. enterprise is the extented stable version and consumer the stable version.

Now u got the  100.x version :-)
![image](https://user-images.githubusercontent.com/59874195/164028198-62655937-b685-4f41-aa2c-87b14b66b5f1.png)
