### ISSUE TITLE
Greenshot installation open iexplorer

### ISSUE THREAD

**Issue by thomaskrampe** [Deyda/Evergreen-Script#3]
Installing Greenshot opens a iexplorer.exe at the end of the installation process. Maybe something like `Get-Process  -Name iexplo* |  Stop-Process` might be a good idea.

**Comment by Deyda** [comment]
Because of different standard browsers, this may not be enough.

**Comment by Deyda** [comment]
Version 2.08.15 - Add Default Browser kill at Greenshot install
