### ISSUE TITLE
Microsoft Edge old version

### ISSUE THREAD

**Issue by Janstie** [Deyda/Evergreen-Script#34]
Hello, at the moment there is an issue that the script didn't download the newest Microsoft Edge version.
It stuck at the moment at the version 99.0.1150.055, on the stable channel, dev and beta channel seems fine.

**Comment by Deyda** [comment]
I change the version from enterprise to consumer. enterprise is the extented stable version and consumer the stable version.

**Comment by Janstie** [comment]
Thank you! Danke!
