### ISSUE TITLE
Adobe Reader DC detection not working/not installing

### ISSUE THREAD

**Issue by zuegler** [Deyda/Evergreen-Script#35]
Hi,

I just tried to install Adobe Reader DC with Version 2.08.08 on a clean Win10 21H2 machine and it seems that there is an issue in detecting it. It won't be installed. See Screenshot below:

![image](https://user-images.githubusercontent.com/104635101/165955976-e660934c-0afd-452f-acb9-22f81323cb2b.png)

**Comment by zuegler** [comment]
Any news regarding this?

**Comment by Deyda** [comment]
With the newest version done. sry for the delay...i was on vacation ^^
