### ISSUE TITLE
getting error The term 'Get-7zip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling  of the name, or if a path was included, verify that the path is correct and try again. At C:\Batch\Evergreen-Script-main\Evergreen.ps1:856 char:18

### ISSUE THREAD

**Issue by rajneeshsaraswat** [Deyda/Evergreen-Script#4]
I am getting attached error
Get-7zip : The term 'Get-7zip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again.
At C:\Batch\Evergreen-Script-main\Evergreen.ps1:856 char:18
+         $7ZipD = Get-7zip | Where-Object { $_.Architecture -eq "$Arch ...
+                  ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-7zip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
![deydaerror](https://user-images.githubusercontent.com/40335999/114015713-2d30cd00-98a9-11eb-8aa2-5f2b9455bf21.PNG)

**Comment by Deyda** [comment]
The Evergreen module has been adjusted. That's how I had to do it in my script. Please use the latest version (version 1.2). The new commands are no longer get-$product (get-7zip), instead get-evergreenapp -name 7zip

**Comment by rajneeshsaraswat** [comment]
Thanks a lot so prompt response mate.
need more help can we have below listed software to be added also.

- Remote Desktop For WVD Url is https://docs.microsoft.com/en-us/azure/virtual-desktop/connect-windows-7-10
- TurboVNC
- TightVNC

**Comment by Deyda** [comment]
is noted on my flipboard. :-)

**Comment by rajneeshsaraswat** [comment]
one more if possible office 2013

**Comment by Deyda** [comment]
That is nevertheless soon end of life. Think that is no longer worth it

**Comment by rajneeshsaraswat** [comment]
yeah i know thta but we have some application which is dependent on that version only, thats why i asked,,

**Comment by rajneeshsaraswat** [comment]
HI,
Did you get chance to include these in your new releae.

Remote Desktop For WVD Url is https://docs.microsoft.com/en-us/azure/virtual-desktop/connect-windows-7-10
TurboVNC
TightVNC
