### ISSUE TITLE
TeamViewer

### ISSUE THREAD

**Issue by sredlin** [Deyda/Evergreen-Script#41]
Teamviewer is downloaded every time, even though the version already downloaded is identical.

Tested with TeamViewer x64.
Version.txt contains 15.30.3

Download TeamViewer x64
Download Version: 15.30.3
Current Version:  
Update available
Starting download of TeamViewer x64 version 15.30.3
Download of the new version 15.30.3 finished!

**Comment by Deyda** [comment]
Fixed with Version 2.09.03
