### ISSUE TITLE
Adobe Reader ist actually a Acrobat DC Package

### ISSUE THREAD

**Issue by Pappnase333** [Deyda/Evergreen-Script#8]
Hi all,

thanks for the good stuff, but I have found an issue. The package Acrobat Reader (German x64, Version Adobe Reader DC 21.007.20091) actually is a binary that installs Adobe Acrobat (Contiuous). Without a licenset, this seems to be OK, but if you happen to have an older full Version of Adobe Acrobat, this will be removed. It looks like the download link is wrong.

Kind regards,

Jens

**Comment by Pappnase333** [comment]
Hi all,

possible candidates for the correct URL are

https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/2100720091/AcroRdrDC2100720091_de_DE.exe

https://get.adobe.com/de/reader/completion/?installer=Reader_DC_2021.007.20091_German_for_Windows&stype=7703&direct=true&standalone=1

I have not found a universal link so far.

Kind regards,

Jens

**Comment by Deyda** [comment]
Correction is implemented in Version 2.05
